
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: planner_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - planner-network

  app:
    build: .
    ports:
      - "8081:8081"
    environment:
      DB_URL: jdbc:postgresql://db:5432/planner_db
      DB_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      DB_PASSWORD: ${DB_PASSWORD}
    depends_on:
      - db
    networks:
      - planner-network

volumes:
  postgres_data:

networks:
  planner-network: