name: CI/CD

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    # НЕ НУЖНО working-directory
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Run tests
        run: mvn test   # mvn теперь видит pom.xml прямо в корне

  healthcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Check health
        run: |
          sleep 30
          curl -f https://planner-api-mwez.onrender.com/actuator/health || exit 1